### ISSUE TITLE
Fast.ai 강의노트 실행 환경설정 관련

### ISSUE THREAD

**Issue by jehyunlee** [fast-ai-kr/ko-translation#15]
**세줄 요약** 입니다.
1. [Fast.ai 강의노트](https://medium.com/@hiromi_suenaga/machine-learning-1-lesson-1-84a1dc2b523)를 실행해보니 실행이 안됨.
2. Fast.ai 버전 문제였고 (0.7 vs 1.0), [작지 않은 이슈](https://forums.fast.ai/t/fastai-v0-7-install-issues-thread/24652)로 판단됨
3. 본 프로젝트가 의미를 가지려면 0.7 환경 설정 글을 추가하거나 1.0 기반 튜토리얼 탐색이 필요함.

--------------

[Hiromi Suenaga의 Fast.ai 강의노트](https://medium.com/@hiromi_suenaga/machine-learning-1-lesson-1-84a1dc2b523)를 실행하기 위해서는 최근 fast.ai 1.0 이 아닌, 0.7 버전이 필요합니다.  

강의에 사용된 fastai module과 function들의 structure가 바뀌거나 deprecate되었기 때문이고,
(여기 계신 모두가 아시겠지만) 공식적으로도 관련 이슈가 공지되었습니다.  
https://forums.fast.ai/t/moving-the-fastai-0-7-folder-do-not-use-pip-for-the-mooc/23667

그런데 fast.ai 0.7 설치 및 실행에도 여러 문제가 있어서 조금은 번잡하네요.
https://forums.fast.ai/t/fastai-v0-7-install-issues-thread/24652

마지막까지 절 당혹스럽게 한 것은 아래 무심코 써있는 cd fastai 부분입니다.
![image](https://user-images.githubusercontent.com/2725349/63306633-6314ec80-c326-11e9-855b-268622401811.png)

그냥 가상환경 설치를 위해 들어가는 디렉토리인 줄 알았는데,
jupyter notebook이든 lab이든 저기 들어가서 실행하지 않으면 예제 코드가 제대로 실행되지 않더라구요.
dependency가 상대경로로 걸려있는 것으로 생각됩니다.

본 페이지가 제공하는 튜토리얼이 의미를 가지기 위해서는 아래 두 가지 중 적어도 하나 이상이 필요할 것 같습니다.
1. 튜토리얼 전에 0.7 관련 환경 설정 글을 하나 추가하기 - 새로 작성
2. version 1.0 기반 튜토리얼을 찾아서 그걸로 올리기

1.은 방금 겪은 삽질을 바탕으로 금방 작성 가능합니다만
2.는 여러분들께서 검색능력을 함께 발휘해주시면 감사하겠습니다.

**Comment by deep-diver** [comment]
딥러닝 강의는 모두 1.0 > 버전으로 교체되었는데, 머신러닝 강의는 아직 0.7 기반이어서 그런것 같습니다. 
1.0 버전으로 어떻게 대체가 될 수 있는지, 2번에 대해서 좀 더 알아봐야 겠군요.

**Comment by jehyunlee** [comment]
일단 Hiromi Suenaga 강의노트는 그대로 번역을 하겠습니다.
1.0으로 컨버팅해서 하기엔 제 실력이 너무 모자라서요.

**Comment by deep-diver** [comment]
Jeremy 본인이 답변한 내용입니다. 
이 답변에 의하면, 0.7과 1.0은 독립적인 버전으로 보는게 맞을것 같습니다.
- 1.0은 딥러닝을 위한것
- 0.7은 딥러닝을 제외한 머신러닝을 위한것
(추후 0.7의 머신러닝 파트가 1.0으로 마이그레이션될 계획이 있는지는 아직 미정인것 같습니다)

제안하신 1번에 대한 내용을 추가하면 될 것 같습니다.

출처: https://forums.fast.ai/t/where-did-fastai-0-7-functions-go-in-fastai-1-0/42621/4

<img width="944" alt="Screen Shot 2019-08-20 at 9 44 30 AM" src="https://user-images.githubusercontent.com/26025527/63308770-28638200-c32f-11e9-8448-042d91360bd6.png">

**Comment by deep-diver** [comment]
제가 예전에 0.7로된 강의를 들을때 번역해둔 문서의 링크입니다. 
이것을 약간 다음어서 등록하면 좋을듯 싶은데, 의견주시면 감사하겠습니다.

https://github.com/deep-diver/fastai-course-korean/blob/master/fastai_lib_intro.md

찾아보니까 Jeremy 본인이 0.7 설치 이슈에 대하여, 방법을 나름 상세히(?) 적어놓은 쓰레드가 있군요.

https://forums.fast.ai/t/fastai-v0-7-install-issues-thread/24652

**Comment by jehyunlee** [comment]
네. 저도 찾아보다가 윗글에 주신 링크들을 찾아 읽었습니다.
그럼 1번으로 진행하겠습니다.
