### ISSUE TITLE
"딥러닝에서 자신을 증명하기위한 학위 대체방안"에 대한 번역은 하지 않으실까요? 

### ISSUE THREAD

**Issue by Joon-Park92** [fast-ai-kr/ko-translation#35]
**여러분이 박사를 고려하기 전에 알아야 할 것들**을 읽은 이후 
[딥러닝에서 자신을 증명하기위한 학위 대체방안 ](https://www.fast.ai/2017/04/06/alternatives/)

글을 번역하였는데 README의 목록에는 없네요. 
혹시 목록에 추가하실 의향이 있으실까요? 
있으시다면 번역글을 push하도록 하겠습니다

**Comment by kkweon** [comment]
같이 한번에 보내주시면 될 것 같아요
